import { spawn, type ChildProcess } from "node:child_process";
import { resolve } from "./resolve.js";
import { parsePort } from "./parse.js";

export interface NatsServerOptions {
  // ── Server ──────────────────────────────────────────────────────────
  /** Port to listen on. -1 = random (default), 0 = nats default (4222). */
  port?: number;
  /** Host to bind to. Default: 127.0.0.1 */
  host?: string;
  /** Server name. Default: auto-generated by NATS */
  serverName?: string;
  /** File to store PID */
  pidFile?: string;
  /** HTTP monitoring port */
  httpPort?: number;
  /** HTTPS monitoring port */
  httpsPort?: number;
  /** Client URL to advertise to other servers */
  clientAdvertise?: string;
  /** Directory to write ports file */
  portsFileDir?: string;

  // ── Logging ─────────────────────────────────────────────────────────
  /** Enable NATS debug output (-D flag) */
  debug?: boolean;
  /** Enable NATS protocol trace (-V flag) */
  trace?: boolean;
  /** Redirect NATS log output to file */
  log?: string;
  /** Timestamp log entries */
  logtime?: boolean;
  /** Log to syslog */
  syslog?: boolean;
  /** Remote syslog address (e.g. udp://localhost:514) */
  remoteSyslog?: string;
  /** Logfile size limit */
  logSizeLimit?: string;
  /** Maximum printable length for traced messages */
  maxTracedMsgLen?: number;

  // ── JetStream ───────────────────────────────────────────────────────
  /** Enable JetStream */
  jetstream?: boolean;
  /** JetStream storage directory */
  storeDir?: string;

  // ── Auth ────────────────────────────────────────────────────────────
  /** Username required for connections */
  user?: string;
  /** Password required for connections */
  pass?: string;
  /** Authorization token required for connections */
  token?: string;

  // ── TLS ─────────────────────────────────────────────────────────────
  /** Enable TLS */
  tls?: boolean;
  /** Server certificate file */
  tlsCert?: string;
  /** Private key for server certificate */
  tlsKey?: string;
  /** Enable TLS with client certificate verification */
  tlsVerify?: boolean;
  /** Client certificate CA for verification */
  tlsCaCert?: string;

  // ── Cluster ─────────────────────────────────────────────────────────
  /** Routes to solicit and connect */
  routes?: string[];
  /** Cluster URL for solicited routes */
  cluster?: string;
  /** Cluster name */
  clusterName?: string;
  /** Do not advertise known cluster information to clients */
  noAdvertise?: boolean;
  /** Cluster URL to advertise to other servers */
  clusterAdvertise?: string;
  /** Number of connect retries for implicit routes */
  connectRetries?: number;
  /** Cluster URL from which members can solicit routes */
  clusterListen?: string;

  // ── Profiling ───────────────────────────────────────────────────────
  /** Profiling HTTP port */
  profile?: number;

  // ── Wrapper ─────────────────────────────────────────────────────────
  /** Forward nats-server stderr to process.stderr. Default: false */
  verbose?: boolean;

  // ── Escape hatches (forward-compat) ─────────────────────────────────
  /** Path to a custom nats.conf file */
  config?: string;
  /** Extra CLI arguments passed to nats-server */
  args?: string[];
}

/**
 * Maps option keys to their nats-server CLI flags.
 * - boolean options: flag is pushed only when true
 * - string/number options: flag + value
 * - string[] options: flag + comma-joined value
 *
 * Keys not in this map are handled separately (host, port, verbose, args).
 */
const FLAG_MAP: Record<string, string> = {
  serverName: "--server_name",
  pidFile: "-P",
  httpPort: "-m",
  httpsPort: "-ms",
  clientAdvertise: "--client_advertise",
  portsFileDir: "--ports_file_dir",
  debug: "-D",
  trace: "-V",
  log: "-l",
  logtime: "-T",
  syslog: "-s",
  remoteSyslog: "-r",
  logSizeLimit: "--log_size_limit",
  maxTracedMsgLen: "--max_traced_msg_len",
  jetstream: "-js",
  storeDir: "-sd",
  user: "--user",
  pass: "--pass",
  token: "--auth",
  tls: "--tls",
  tlsCert: "--tlscert",
  tlsKey: "--tlskey",
  tlsVerify: "--tlsverify",
  tlsCaCert: "--tlscacert",
  routes: "--routes",
  cluster: "--cluster",
  clusterName: "--cluster_name",
  noAdvertise: "--no_advertise",
  clusterAdvertise: "--cluster_advertise",
  connectRetries: "--connect_retries",
  clusterListen: "--cluster_listen",
  profile: "--profile",
  config: "-c",
};

export function buildArgs(opts: NatsServerOptions): string[] {
  const host = opts.host ?? "127.0.0.1";
  const port = opts.port ?? -1;
  const args = ["-a", host, "-p", String(port)];

  for (const [key, flag] of Object.entries(FLAG_MAP)) {
    const val = (opts as Record<string, unknown>)[key];
    if (val === undefined || val === false) continue;
    if (val === true) {
      args.push(flag);
    } else if (Array.isArray(val)) {
      args.push(flag, val.join(","));
    } else {
      args.push(flag, String(val));
    }
  }

  if (opts.args) args.push(...opts.args);
  return args;
}

export class NatsServer {
  /** Full NATS connection URL (e.g. nats://127.0.0.1:52431) */
  readonly url: string;
  /** Assigned port */
  readonly port: number;
  /** Resolves with the exit code when the process exits (for crash detection) */
  readonly exited: Promise<number | null>;

  private proc: ChildProcess;

  private constructor(proc: ChildProcess, host: string, port: number) {
    this.proc = proc;
    this.port = port;
    this.url = `nats://${host}:${port}`;
    this.exited = new Promise((res) => {
      proc.on("exit", (code) => res(code));
    });
  }

  static async start(opts: NatsServerOptions = {}): Promise<NatsServer> {
    const bin = resolve();
    const args = buildArgs(opts);
    const host = opts.host ?? "127.0.0.1";

    const proc = spawn(bin, args, {
      stdio: ["ignore", "ignore", "pipe"],
    });

    const assignedPort = await new Promise<number>((resolve, reject) => {
      const timeout = setTimeout(() => {
        proc.kill("SIGKILL");
        reject(new Error("nats-server did not start within 5s"));
      }, 5000);

      proc.on("error", (err) => {
        clearTimeout(timeout);
        reject(err);
      });

      proc.on("exit", (code) => {
        clearTimeout(timeout);
        reject(new Error(`nats-server exited with code ${code} before ready`));
      });

      let buffer = "";
      proc.stderr!.on("data", (chunk: Buffer) => {
        const text = chunk.toString();
        if (opts.verbose) process.stderr.write(text);
        buffer += text;
        const lines = buffer.split("\n");
        buffer = lines.pop()!;
        for (const line of lines) {
          const parsed = parsePort(line);
          if (parsed !== null) {
            clearTimeout(timeout);
            // Stop listening for exit as an error once we have the port
            proc.removeAllListeners("exit");
            resolve(parsed);
            return;
          }
        }
      });
    });

    return new NatsServer(proc, host, assignedPort);
  }

  /** Gracefully stop the server (SIGTERM → 5s timeout → SIGKILL) */
  async stop(): Promise<void> {
    if (this.proc.exitCode !== null) return;
    this.proc.kill("SIGTERM");
    const exited = await Promise.race([
      this.exited.then(() => true),
      new Promise<false>((r) => setTimeout(() => r(false), 5000)),
    ]);
    if (!exited) {
      this.proc.kill("SIGKILL");
      await this.exited;
    }
  }
}

export { resolve as resolveBinary } from "./resolve.js";
